<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Label="Aspire">
    <PackageVersion Include="Aspire.Hosting" Version="13.4.3" />
    <PackageVersion Include="Aspire.Hosting.Azure.Functions" Version="13.4.3" />
    <PackageVersion Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.RavenDB" Version="13.4.0" />
    <PackageVersion Include="CommunityToolkit.Aspire.RavenDB.Client" Version="13.4.0" />
  </ItemGroup>
  <ItemGroup Label="Azure Functions">
    <PackageVersion Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.51.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.5.4" />
    <PackageVersion Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
  </ItemGroup>
  <ItemGroup Label="Microsoft Extensions">
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.7.0" />
  </ItemGroup>
  <ItemGroup Label="OpenTelemetry">
    <PackageVersion Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
  </ItemGroup>
  <ItemGroup Label="RavenDB">
    <PackageVersion Include="RavenDB.Client" Version="7.2.5" />
    <PackageVersion Include="RavenMigrations" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup Label="Other">
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Spectre.Console" Version="0.56.1-alpha.0.2" />
    <PackageVersion Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>
</Project>